apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-hats.yaml
- deployment-left-arm.yaml
- deployment-left-leg.yaml
- deployment-main.yaml
- deployment-right-arm.yaml
- deployment-right-leg.yaml
- service-hats.yaml
- service-left-arm.yaml
- service-left-leg.yaml
- service-main.yaml
- service-right-arm.yaml
- service-right-leg.yaml
- serviceaccount.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: podtato-head
